[project]
name = "yolov7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "coremltools>=8.3.0",
    "ipython>=8.37.0",
    "matplotlib>=3.2.2",
    "numpy>=1.18.5,<1.24.0",
    "onnx>=1.17.0",
    "onnx-graphsurgeon>=0.5.8",
    "onnx-simplifier>=0.4.36",
    "onnxruntime>=1.23.2",
    "onnxruntime-gpu>=1.23.2",
    "onnxsim>=0.4.36",
    "opencv-python>=4.1.1",
    "opencv-python-headless>=4.8.1.78",
    "pandas>=1.1.4",
    "pillow>=7.1.2",
    "protobuf<4.21.3",
    "psutil>=7.1.3",
    "pyyaml>=5.3.1",
    "requests>=2.23.0",
    "scipy>=1.4.1",
    "seaborn>=0.11.0",
    "tensorboard>=2.4.1",
    "thop>=0.1.1.post2209072238",
    "torch>=1.7.0,!=1.12.0",
    "torchvision>=0.8.1,!=0.13.0",
    "tqdm>=4.41.0",
]
